# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mandy Chen
email: mandychen.art (@) gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software engineering, Visual media, Illustration, Musicianship, and Whole food plant-based recipes.

author: Mandy Chen
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://picaq.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: picaq2
# github_username:  picaq
# Color scheme supports "light" (default) and "dark"
# color_scheme: dark
# color_scheme: foo


# Build settings
# theme: minima
# nav_external_links:
#   - title: "@picaq"
#     url: "https://github.com/picaq"
#     hide_icon: false 
#     opens_in_new_tab: true 
#   - title: "in/mandy-chen-picaq"
#     url: "https://www.linkedin.com/in/mandy-chen-picaq/"
#     hide_icon: false 
#     opens_in_new_tab: true 
#   - title: "x/picaq2"
#     url: "https://twitter.com/picaq2"
#     hide_icon: false # set to true to hide the external link icon - defaults to false
#     opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

theme: just-the-docs #  for local development only! saved in _config_dev.yml
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

head:
  custom_css:
    - assets/css/just-the-docs-custom.css  # Theme will auto-load this
    - assets/css/just-the-docs-switchable.css
defaults:
  - scope:
      path: "" # All files
    values:
      layout: default


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 4
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s\./]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "This site uses <a href='https://github.com/just-the-docs/just-the-docs' target='blank'>Just the Docs</a>, a documentation theme for Jekyll."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/picaq/picaq.github.io" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
